- name: check disk space
  tasks:
    - name: get disk usage
      ansible.builtin.command: df -h
      register: disk_usage

    - name: check disk space available
      ansible.builtin.shell: df -Ph / | awk 'NR==2 {print $5}'
      register: disk_usage_percent
